import { DriveFolder, Product } from '@/types/store';

export const DEMO_FOLDERS: DriveFolder[] = [
  { id: 'folder-abiti', name: 'Abiti & Vestiti', slug: 'abiti-e-vestiti', count: 4 },
  { id: 'folder-giacche', name: 'Giacche & Trench', slug: 'giacche-e-trench', count: 3 },
  { id: 'folder-camicie', name: 'Camicie & Top', slug: 'camicie-e-top', count: 3 },
  { id: 'folder-pantaloni', name: 'Pantaloni & Denim', slug: 'pantaloni-e-denim', count: 3 },
  { id: 'folder-accessori', name: 'Borse & Accessori', slug: 'borse-e-accessori', count: 3 },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-1',
    name: 'Abito Midi in Seta Floreale',
    price: 89.0,
    originalPrice: 119.0,
    folderId: 'folder-abiti',
    folderName: 'Abiti & Vestiti',
    imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=500&q=80',
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    isNew: true,
    isSale: true,
    description: 'Abito elegante midi in pura seta con fantasia floreale acquerellata, scollo a V e cintura coordinata.',
  },
  {
    id: 'demo-2',
    name: 'Vestito Minimalista Drappeggiato',
    price: 75.0,
    folderId: 'folder-abiti',
    folderName: 'Abiti & Vestiti',
    imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=500&q=80',
    sizes: ['S', 'M', 'L'],
    inStock: true,
    isNew: true,
    description: 'Linee pulite ed essenziali per questo abito con elegante motivo a drappeggio laterale.',
  },
  {
    id: 'demo-3',
    name: 'Abito Lungo da Sera Plissé',
    price: 135.0,
    originalPrice: 160.0,
    folderId: 'folder-abiti',
    folderName: 'Abiti & Vestiti',
    imageUrl: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=500&q=80',
    sizes: ['S', 'M', 'L'],
    inStock: true,
    isSale: true,
    description: 'Meraviglioso abito serale plissettato, ideale per eventi esclusivi e cerimonie importanti.',
  },
  {
    id: 'demo-4',
    name: 'Vestito Chemisier in Cotone',
    price: 59.9,
    folderId: 'folder-abiti',
    folderName: 'Abiti & Vestiti',
    imageUrl: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=500&q=80',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    description: 'Casual chic per tutti i giorni: abito chemisier a manica lunga con bottoni in madreperla e cintura coordinata.',
  },
  {
    id: 'demo-5',
    name: 'Blazer Sartoriale Doppiopetto',
    price: 110.0,
    originalPrice: 140.0,
    folderId: 'folder-giacche',
    folderName: 'Giacche & Trench',
    imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=500&q=80',
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    isNew: true,
    isSale: true,
    description: 'Blazer strutturato con rever a lancia, taglio sartoriale impeccabile e bottoni dorati in rilievo.',
  },
  {
    id: 'demo-6',
    name: 'Trench Coat Iconico Beige',
    price: 145.0,
    folderId: 'folder-giacche',
    folderName: 'Giacche & Trench',
    imageUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=500&q=80',
    sizes: ['S', 'M', 'L'],
    inStock: true,
    description: 'Impermeabile classico intramontabile in twill di cotone con bavolet e cintura con fibbia rivestita.',
  },
  {
    id: 'demo-7',
    name: 'Giacca Biker in Similpelle',
    price: 79.9,
    folderId: 'folder-giacche',
    folderName: 'Giacche & Trench',
    imageUrl: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&w=500&q=80',
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    description: 'Giacca stile biker con zip asimmetrica, tasche sagomate e dettagli metallici finitura argento lucido.',
  },
  {
    id: 'demo-8',
    name: 'Camicia in Puro Lino Naturale',
    price: 49.0,
    folderId: 'folder-camicie',
    folderName: 'Camicie & Top',
    imageUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=500&q=80',
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    isNew: true,
    description: 'Camicia traspirante e fresca in puro lino con colletto alla francese e vestibilità rilassata.',
  },
  {
    id: 'demo-9',
    name: 'Blusa Satin con Fiocco',
    price: 45.0,
    folderId: 'folder-camicie',
    folderName: 'Camicie & Top',
    imageUrl: 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?auto=format&fit=crop&w=500&q=80',
    sizes: ['XS', 'S', 'M'],
    inStock: true,
    description: 'Top elegante in raso lucido con colletto lavallière annodabile e maniche a palloncino.',
  },
  {
    id: 'demo-10',
    name: 'Top a Costine Senza Maniche',
    price: 29.9,
    folderId: 'folder-camicie',
    folderName: 'Camicie & Top',
    imageUrl: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=500&q=80',
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    description: 'Canotta essenziale in maglia fine a costine, ideale sia da sola che sotto blazer e cardigan.',
  },
  {
    id: 'demo-11',
    name: 'Pantaloni a Gamba Larga Palazzo',
    price: 64.0,
    folderId: 'folder-pantaloni',
    folderName: 'Pantaloni & Denim',
    imageUrl: 'https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?auto=format&fit=crop&w=500&q=80',
    sizes: ['S', 'M', 'L'],
    inStock: true,
    isNew: true,
    description: 'Pantaloni a vita alta con pinces frontali e taglio fluido extra-wide per una silhouette slanciata.',
  },
  {
    id: 'demo-12',
    name: 'Jeans Vintage Straight Cut',
    price: 59.0,
    originalPrice: 75.0,
    folderId: 'folder-pantaloni',
    folderName: 'Pantaloni & Denim',
    imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=500&q=80',
    sizes: ['26', '28', '30', '32', '34'],
    inStock: true,
    isSale: true,
    description: 'Denim classico in cotone con lavaggio medio vintage, vita media e linea dritta alla caviglia.',
  },
  {
    id: 'demo-13',
    name: 'Pantaloni Chino Slim Fit',
    price: 54.0,
    folderId: 'folder-pantaloni',
    folderName: 'Pantaloni & Denim',
    imageUrl: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=500&q=80',
    sizes: ['44', '46', '48', '50'],
    inStock: true,
    description: 'Pantaloni chino in gabardina elasticizzata con tasche a filo posteriori e chiusura con zip e bottone.',
  },
  {
    id: 'demo-14',
    name: 'Borsa a Tracolla in Pelle Martellata',
    price: 95.0,
    originalPrice: 120.0,
    folderId: 'folder-accessori',
    folderName: 'Borse & Accessori',
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=500&q=80',
    sizes: ['Unica'],
    inStock: true,
    isSale: true,
    description: 'Borsa artigianale compatta con tracolla regolabile, chiusura a scatto e finiture dorate lucide.',
  },
  {
    id: 'demo-15',
    name: 'Shopping Bag Canvas & Cuoio',
    price: 68.0,
    folderId: 'folder-accessori',
    folderName: 'Borse & Accessori',
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=500&q=80',
    sizes: ['Unica'],
    inStock: true,
    isNew: true,
    description: 'Tote bag capiente in pesante canvas di cotone con manici rinforzati in vero cuoio.',
  },
  {
    id: 'demo-16',
    name: 'Occhiali da Sole Tartarugati',
    price: 39.0,
    folderId: 'folder-accessori',
    folderName: 'Borse & Accessori',
    imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=1000&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=500&q=80',
    sizes: ['Unica'],
    inStock: true,
    description: 'Montatura rétro tartarugata in acetato con lenti polarizzate UV400 ad alta protezione solare.',
  },
];
